#ansible installs these modules in manage nodes and excute them using python.
--- 
- hosts: all
  become: true
  tasks:
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0644'   #Web servers like Nginx or Apache run as non-root users, so setting file permission to 0644 ensures 
        they have read access to serve content while restricting write access for security.
